configs: imx93-phyboard-segin: Add missing CPU configs
Add missing CONFIG_CPU and CONFIG_CPU_IMX options. This fixes linker
error "undefined reference to `print_cpuinfo'" since print_cpuinfo
from NXP is not properly guarded with compiler ifdefs.

Signed-off-by: Primoz Fiser <primoz.fiser@norik.com>
Signed-off-by: Christian Hemp <c.hemp@phytec.de>