rng: ele: Fix missing include files
Add missing include files to fix ele-rng driver build. Fixes the
following compiler errors:

 error: implicit declaration of function 'memalign' [-Wimplicit-function-declaration]
 error: implicit declaration of function 'free' [-Wimplicit-function-declaration]
 error: 'ARCH_DMA_MINALIGN' undeclared (first use in this function)

Signed-off-by: Primoz Fiser <primoz.fiser@norik.com>
Signed-off-by: Christian Hemp <c.hemp@phytec.de>